Repository joeljsv/hacktober2021, pull requests merged in 2021-10, with the labels that each got.

#1 Create mergeSort.cpp
  cpp_codes/mergeSort.cpp
Labels: good first issue, hacktoberfest-accepted

#3 Nth Fibonacci number using recursion
  Fibonacci series using recursion
Labels: good first issue, hacktoberfest-accepted

#4 Create Binary Search
  cpp_codes/Binary Search
Labels: good first issue, hacktoberfest-accepted

#5 added tic tac toe game code in cpp language folder
  cpp_codes/tictactoe.cpp
Labels: good first issue, hacktoberfest-accepted

#6 Create Bubble Sort code in CPP
  cpp_codes/Bubble Sort code in CPP
Labels: good first issue, hacktoberfest-accepted

#7 Create Armstrong Number
  cpp_codes/Armstrong Number
Labels: hacktoberfest-accepted

#9 Day_converter is added
  cpp_codes/day_converter.cpp
Labels: hacktoberfest-accepted

#10 merge_operations_palindrome.cpp
  cpp_codes/merge_operations_palindrome.cpp
Labels: hacktoberfest-accepted

#11 linked list reversal
  cpp_codes/linkedlistreversal.cpp
Labels: hacktoberfest-accepted, hacktober

#14 add php bin checker code
  php_codes/bin_checker.php
Labels: hacktoberfest-accepted

#13 Add files via upload
  cpp_codes/Ceiling Sum.cpp
Labels: hacktoberfest-accepted

#15 Create Insertion_Sort.cpp
  cpp_codes/Insertion_Sort.cpp
Labels: hacktoberfest-accepted

#16 Create Floyd_triangle.cpp
  cpp_codes/Floyd_triangle.cpp
Labels: hacktoberfest-accepted

#17 Added Send SMS and Email
  Python_codes/Send Email/main.py
  Python_codes/Send sms/main.py
Labels: hacktoberfest-accepted

#19 Fibbonnacci series
  cpp_codes/Fibonnaci.cpp
Labels: hacktoberfest-accepted

#18 Create 0-1 Knapsack.cpp
  cpp_codes/0-1 Knapsack.cpp
Labels: hacktoberfest-accepted

#27 Added Round Robin algorithm
  Round Robin
Labels: hacktoberfest-accepted

#28 bfs.py
  Python_codes/bfs.py
Labels: hacktoberfest-accepted

#30 Create hashingwithchaining.cpp
  cpp_codes/hashingwithchaining.cpp
Labels: hacktoberfest-accepted

#29 insertion sort
  insertion sort
Labels: hacktoberfest-accepted

#31 Binary Search
  cpp_codes/bs.cpp
Labels: hacktoberfest-accepted

#35 Binary Search
  Python_codes/bs.py
Labels: hacktoberfest-accepted

#38 Create quick sort.cpp
  cpp_codes/heap sort.cpp
  cpp_codes/quick sort.cpp
Labels: hacktoberfest-accepted

#40 Added a new python file
  Python_codes/Fibonacci.py
Labels: hacktoberfest-accepted

#42 Balanced parentheses in an expression (well-formedness) using Stack Added
  cpp_codes/Balanced Parentheses(stack).cpp
Labels: hacktoberfest-accepted

#43 Tic_Tac_Toe_game.py
  Python_codes/Tic_Tac_Toe_game.py
Labels: hacktoberfest-accepted

#47 CryptoGraphy Basics Codes Added
  Python_codes/CryptoGraphy/additive_cipher.py
  Python_codes/CryptoGraphy/additive_inverse.py
  Python_codes/CryptoGraphy/extended_euc_alg.py
  Python_codes/CryptoGraphy/mod.py
  Python_codes/CryptoGraphy/multiplicative_cipher.py
  Python_codes/CryptoGraphy/multiplicative_inverse.py
  Python_codes/CryptoGraphy/readme.md
Labels: hacktoberfest-accepted

#48 Create cricket_game.cpp
  cpp_codes/cricket_game.cpp
Labels: hacktoberfest-accepted

#53 C++ Program to cheak Palindrome Number
  Palindrome number.cpp
Labels: hacktoberfest-accepted

#58 Create Factorial.cpp
  cpp_codes/Factorial.cpp
Labels: hacktoberfest-accepted

#61 Dec to binary using stack
  cpp_codes/Dec to binary using stack
Labels: hacktoberfest-accepted

#62 Centimetres conversion
  cpp_codes/Centimetres conversion
Labels: hacktoberfest-accepted

#66 Add files via upload
  cpp_codes/ADADISH.cpp
Labels: no- description

#77 International Space Station tracking WebApp.
  JavaScript_codes/iss-tracker/Readme.md
  JavaScript_codes/iss-tracker/app.js
  JavaScript_codes/iss-tracker/index.html
  JavaScript_codes/iss-tracker/screenshots/iss-tracker-home.png
  JavaScript_codes/iss-tracker/screenshots/iss-tracker-working.png
Labels: hacktoberfest-accepted

#83 Rotation Count in rotated sorted array.cpp
  cpp_codes/Rotation Count in rotated sorted array.cpp
Labels: hacktoberfest-accepted
